# Site settings
title: Binary Analysis Team, Institute of Information Engineering
email: iiebat@sina.com
github_username:  iiebat

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_datia"]
